name: Run webhook

on: 
  push: 
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute webhook for netlify deployment
        run: echo test
