name: Run tttt

on: 
  schedule:
    - cron: '* * * * *'  # every hour

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute webhook for netlify deployment
        run: echo 'test every minute'
